# Generated by Django 3.2.6 on 2021-12-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_api', '0002_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='title',
            new_name='title1',
        ),
    ]
